namespace :es do
  desc 'Count all documents in the reggae section'
  task 'count_reggae' do
    raise 'NYI'

    res = %x[]
    puts res
  end

  desc 'Count docs in the whole music index'
  task 'count_music' do
    raise 'NYI'

    res = %x[]
    puts res
  end

  desc 'Find reggae song with id=1'
  task 'reggae_1' do
    raise 'NYI'

    res = %x[]
    puts res
  end

  desc 'Find all songs that contain Dragon'
  task 'all_dragon' do
    raise 'NYI'

    res = %x[]
    puts res
  end

  desc 'Find all songs that contain Running'
  task 'all_running' do
    raise 'NYI'

    res = %x[]
    puts res
  end

  desc 'Find all songs that contain Run'
  task 'all_run' do
    raise 'NYI'

    res = %x[]
    puts res
  end

  desc 'Show current mappings for reggae doc types'
  task 'mappings' do
    raise 'NYI'

    res = %x[]
    puts res
  end

  desc 'Create new custom mapping to handle the run issue'
  task 'cust_mappings' do
    raise 'NYI'

    res = %x[]
    puts res
  end
end
